// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjScdRTppPsV7zseJ65HsgfIdwdvgAiok',
    appId: '1:786215154133:web:8b40c16f5cab4ff5b78d5c',
    messagingSenderId: '786215154133',
    projectId: 'studhub-340123',
    authDomain: 'studhub-340123.firebaseapp.com',
    databaseURL: 'https://studhub-340123-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'studhub-340123.appspot.com',
    measurementId: 'G-DW2R330YF6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcyiQuXSYk7noO_mLbrvh2MSl23KbNwOU',
    appId: '1:786215154133:android:e1b8fcb806144f5bb78d5c',
    messagingSenderId: '786215154133',
    projectId: 'studhub-340123',
    databaseURL: 'https://studhub-340123-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'studhub-340123.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwqnLRW83z117-EiJhUzgfy-wKbP6hga8',
    appId: '1:786215154133:ios:ecdf8e9741376784b78d5c',
    messagingSenderId: '786215154133',
    projectId: 'studhub-340123',
    databaseURL: 'https://studhub-340123-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'studhub-340123.appspot.com',
    iosClientId: '786215154133-d9ijcvpbslhl7evifc8osh5ehos484l7.apps.googleusercontent.com',
    iosBundleId: 'com.example.studhub',
  );
}
